### PR TITLE
Fix off by one errors when finding packages to copy

### PR DESCRIPTION
**Pull request by sindrig**
3 off-by-one errors causes getPackagesToCopy to miss a lot of packages that should be shipped with node_modules

### CODE REVIEW

**Comment by sindrig** [comment]
Not sure why the first commit failed security audit - if it was erroneous and you want it in, let me know and I'll remove the 2nd commit.

**Comment by sindrig** [comment]
@Brian-McBride we're actively reviewing and fixing bugs while trying to integrate this with island-is/island.is. At the moment we've started publishing our own versions of esbuildnx.

**Comment by Brian-McBride** [comment]
I'm sorry sindrig, I was OOO for the last week and didn't see your PRs. 
I'm happy to add you as a maintainer and set the project up with a proper CI/CD to publish out as well;

**Comment by Brian-McBride** [comment]
I'll be able to set up the CI/CD by tomorrow, likely later today to the NPM repo.

**Comment by sindrig** [comment]
Sounds good! No worries, I'll keep our setup like is for now and create PRs from my fork if there are more changes we need.

**Comment by sindrig** [comment]
I'll gladly accept maintainer status as well :)

**Pull request merged**
